### ISSUE TITLE
Could you make a step by step tutorial?

### ISSUE THREAD

**Issue by pr110** [shellbear/web-watcher#2]
I am stuck trying to figure out how to implement the code. Do I need Golang?

**Comment by shellbear** [comment]
Hello, sorry I was very busy

Yes I update the documentation and fix some bugs!

I will close the issue when it will be done.

**Comment by pr110** [comment]
Thanks @shellbear

**Comment by shellbear** [comment]
The code has been updated and multiple issues were fixed.
Documentation is now available here: https://shellbear.github.io/web-watcher/.
