### ISSUE TITLE
Your request could not be authenticated by the GitHub Packages service

### ISSUE THREAD

**Issue by petercockroach** [shellbear/web-watcher#4]
```
docker pull docker.pkg.github.com/shellbear/web-watcher/web-watcher
Using default tag: latest
Error response from daemon: Head https://docker.pkg.github.com/v2/shellbear/web-watcher/web-watcher/manifests/latest: no basic auth credentials
```
When going to https://docker.pkg.github.com/v2/shellbear/web-watcher/web-watcher/manifests/latest, my github credentials don't seem to work.

**Comment by shellbear** [comment]
Hello, really sorry for delay.

As explained in this [post](https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358/19).

I recommend you to clone the repo and build the image locally or use Github credentials to pull the image, as explained [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-docker-registry#authenticating-to-github-packages).

I will update the instructions to make it more clear.

Thanks for reporting 👍
